### ISSUE TITLE
Data currently unavailable

### ISSUE THREAD

**Issue by msman0** [glennmckechnie/weewx-WXgraphic#4]
Hi, I get the error 
Data currently unavailable

The path in config.txt is correct and I have installed weeWX Versiono 4.10.2
The file wxgraphic_weewx.txt is also available at the server.
I don't use clientraw at the moment

How can I fix the error?

Thank you very much!

**Comment by glennmckechnie** [comment]
A good question.

You're seeing that message on the image, in red letters?

I'm assuming from your comments that you've looked at the code and found that particular message at line 86 in _WXgraphic/index.php_ 

It is raised when **$dataraw** is empty. It tries twice to look for and read  **$data_file_path** and on the 3rd try it prints that string in a red font within the image.

That points to the  **$data_file_path** variable on your webserver being incorrect, empty or invalid.

The best way to see immediately if that string is correct is to cut and paste it, directly from the config.txt file, into a terminal on the webserver computer and **ls** or **cat** it.  If you get success then it is indeed correct and points to the correct file - providing the contents are formatted correctly?

The cut and paste removes any chance of typos intervening - ie: human nature. Happens to us all.
 
**ls** will prove that the operating system can find it, **cat** will show whether it has content.

The next step is to check the permissions of that file. if the running webserver can't read it then index.php won't be able to read it either. So check the permissions.

Is this webserver running on the same machine as the template file is being generated. ie: - Do the paths translate between machines? 

If it's still not working then send me the webservers _wxgraphic/config.txt_, _wxgraphic/index.php_ and _wxgraphic/DATA/wxgraphic_weewx.txt_ files
Also the _weewx/skins/Wxgraphic/skin.conf_ and _weewx/skins/Wxgraphic/config.txt.tmpl_ files
With that I'll see if I can reproduce the error here.

**Comment by msman0** [comment]
Hi, thank you very much for your help. You are right, I had a wrong (not the complete) path in the file.

Now it works...only the character ° is not displayed. I have done it also with hexer in the index.php. 

Great work!

**Comment by glennmckechnie** [comment]
Excellent.

Regarding the  ° character. It's hard to know what is going on there.

Its hex b0 (b zero) and should display as the  [ASCII character  ° ](https://www.rapidtables.com/convert/number/hex-to-ascii.html). Follow that link to display b0 under various encodings.
Does it show in the index.php file as  ° when viewed using vi/vim?

If it does then it may be your webserver messing with it, which adds another layer of complication. Like I say ... hard to know.  If it's showing as ? icon or a mini playing card :-) then it's being interpreted incorrectly. (see the link above)

After you've used hexer (and mcview from midnight commander will also show it) are you viewing/saving it with another editor? I know vi/vim/gvim works. Neither nano nor pico will display it correctly, although they appear to save the file okay

**Comment by msman0** [comment]
Hi thanks and sorry for the late reply. It works on an other webserver correct. Fantastic tool and best support from you!
